### ISSUE TITLE
改善跳题策略

### ISSUE THREAD

**Issue by foresee-io** [ouxu/oj-pro#15]
例如：
`http://newoj.acmclub.cn/problems/1001`
导航会显示“问题不存在”。殊不知用户点击“上一题”“下一题”按钮时，由于题号未必连续，会经常遇见此导航错误页。

可能的改善措施：
【基础】自动找到最近 且 真实存在的题号，提示用户“x秒之内自动进入”
【进阶】将这些放在后台进行，让用户“无感操作”

**Comment by ouxu** [comment]
已发布
